= UChen Links 

== Leanne's Repos

 * https://github.com/leannenorthrop/classical-tibetan[Classical Tibetan]
 * https://github.com/leannenorthrop/markdown-js/blob/wylie/src/dialects/wylie/wmd2uchen.js[UChen Map]
 * http://leannenorthrop.github.io/classical-tibetan/editor/?layout=contrib#[Markdowb Tibetan Editor]
 * http://leannenorthrop.github.io/classical-tibetan/[Sample Page ]of Tibetan
 * http://bohoomil.com/doc/05-fonts/[Bohoomil Fonts]
 * https://sites.google.com/site/chrisfynn2/home/fonts/jomolhari[Jomolhari Fonts]
 * http://groovy.codehaus.org/jsr/spec/AltChapter03LexicalStructure.html[Groovy Fonts] Overview
 * http://www.unicode.org/versions/Unicode7.0.0/ch13.pdf[Unicode Overview of UChen Syntax] - see page 499-501
 * http://unicode.org/charts/PDF/U0F00.pdf[Unicode PDF] - see page 2 and 3

== UChen Logic

Have done an addition to the FreeMP3 suite. This logic allows the pronunciation of UChen (or any) sound fragments. The new groovy module named MP3Player has been included to play these sound fragments. A simple code sample to use this feature would look like this:

.Play A Sound
[source,groovy]
----
MP3Player mp3 = new MP3Player();
mp3.playSound('sounds/F5E.mp3') 
mp3.play('F53')  // actually translated to look for a sound fragment as 'sounds/F53.mp3' 
----

To use this MP3Player, we need an .mp3 file. These can be created on Apple Mac OSX systems using the QuickTime Player to record audio thru the Mac microphone. Then save it as a .m4a audio (not movie) file. This must be changed into a .mp3 file using a free tool here http://www.nch.com.au/switch/index.html?gclid=CKbEtY6Ex7QCFW3KtAod-TYAlQ[called Switch]. That tool reads a .m4a file and writes a .mp3 equivalent. 

See *'resources/fontmap.uchen'* for a map of UChen sylables to unicode characters. The Unicode character like, for example, *UChenMap["ch"] = "\u0F46";* would need a sound file named 'sounds/F46.mp3' so convert the sound fragment and name it according to the unicode character it represents.

== Apple Mac OSX and Sound Synthesis

There are tools on the Apple to allow disabled users better access. One of these tools if http://www.apple.com/accessibility/osx/voiceover/[VoiceOver for OSX]. It offers a nice demo of text-to-speech features. Tools like this can be accessed from the javax.accessibility package with Apple's version of Java. You can hear one such sample here: +++
<h3>Anna</h3>
<P>
<script language="JavaScript" src="http://www.explainthatstuff.com/audio/audio-player.js"></script><object type="application/x-shockwave-flash" data="http://www.explainthatstuff.com/audio/player.swf" id="audioplayer3" height="24" width="290">
<param name="movie" value="http://www.explainthatstuff.com/audio/player.swf">
<param name="FlashVars" value="playerID=3&amp;bg=0xBCB19B&amp;leftbg=0xFF0000&amp;lefticon=0x111111&amp;rightbg=0xFF0000&amp;rightbghover=0xDCDBDC&amp;righticon=0x111111&amp;righticonhover=0xCC4321&amp;text=0x666666&amp;slider=0x666666&amp;track=0xFFFFFF&amp;border=0x666666&amp;loader=0x9FFFB8&amp;soundFile=http://www.explainthatstuff.com/audio/iloveanna.mp3">
<param name="quality" value="high">
<param name="menu" value="false">
<param name="wmode" value="transparent">
</object> 
</P>
+++ and it's called Anna. See http://www.explainthatstuff.com/how-speech-synthesis-works.html[Explain That Stuff] for more info.

In the 1980's, Texas Instruments developed a tool to let children learn to spell english words by speaking to the child. This tool was the *Speak-and-Spell* and you can http://www.speaknspell.co.uk/speaknspell.html[try it out yourself here.]

''' 


